import {processVideo} from './engine.js';
import {getDriveMetadata} from './drive.js';
import {attachActions,assertCoverage,assertCaptureReferences,captureReference} from './trace.js';
import {$,$$,bytes,ext,isVideoName,safeName,downloadBlob,jsonBlob,debounce,esc} from './utils.js';
import {idbGet,idbSet,idbClear} from './storage.js';
import {buildRecord,extractGuideStructure} from './file-reader.js';
import {analyzeLocal,generateDraftLocal,regenerateSection,auditLocal,renderTranscriptAsSource,normalizeFinal} from './local-ai.js';
import {connectDrive,isDriveConnected,downloadDriveFile} from './drive.js';
import {createDocx,createPdf} from './documents.js';
import {setCloudConfig,cloudJSON} from './cloud-api.js';

const base=window.BOT_CONFIG||{};
const SETTINGS_KEY='bot_documental_v18_cloud_settings';
const TOKEN_KEY='bot_documental_v18_app_token';
const defaultSettings={model:'gemini-3.7-flash',videoModel:'gemini-3.7-flash',googleClientId:'',backendUrl:''};
let settings={...defaultSettings,...JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}')};
const state={sourceMode:'local',guideFiles:[],guides:[],sourceFile:null,sourceRecord:null,videoFile:null,videoTranscript:null,analysis:null,answers:[],finalDocument:null,audit:null,docxBlob:null,pdfBlob:null,driveMeta:null,engineJob:null};

function toast(msg,type='good',ms=3600){const d=document.createElement('div');d.className=`toast ${type}`;d.textContent=msg;$('#toastHost').appendChild(d);setTimeout(()=>d.remove(),ms)}
function warn(host,msg){const x=document.createElement('div');x.className='warning';x.textContent=msg;host.appendChild(x)}
function setStep(n){$$('.step').forEach((x,i)=>x.classList.toggle('active',i<n))}
function show(el,on=true){(typeof el==='string'?$(el):el)?.classList.toggle('hidden',!on)}
function configureCloud(){setCloudConfig({backendUrl:settings.backendUrl,appToken:sessionStorage.getItem(TOKEN_KEY)||''});}
function cfgReady(){configureCloud();const ready=!!settings.backendUrl;$('#apiStatus').textContent=ready?'IA cloud configurada':'Configura backend cloud';$('#apiStatus').className='status-chip '+(ready?'good':'warn');return ready;}
function progressStart(title){show('#progressPanel',true);$('#progressTitle').textContent=title;$('#progressLog').innerHTML='';setProgress(0,'Iniciando…');$('#progressPanel').scrollIntoView({behavior:'smooth',block:'start'})}
function setProgress(p,msg){p=Math.max(0,Math.min(1,p));$('#progressBar').style.width=`${Math.round(p*100)}%`;$('#progressPercent').textContent=`${Math.round(p*100)}%`;if(msg){const log=$('#progressLog');if(log.lastElementChild?.dataset.message!==msg){const d=document.createElement('div');d.dataset.message=msg;d.textContent=`${new Date().toLocaleTimeString()} · ${msg}`;log.appendChild(d);while(log.children.length>300)log.firstElementChild.remove();}log.scrollTop=log.scrollHeight}}
function progressEnd(){setProgress(1,'Listo.');setTimeout(()=>show('#progressPanel',false),800)}
function fail(e){console.error(e);show('#progressPanel',false);toast(String(e?.message||e),'bad',6500)}
function ensureApi(){if(!settings.backendUrl)throw new Error('Configura la URL del backend Cloudflare Worker.');if(!settings.model||!settings.videoModel)throw new Error('Selecciona los modelos Gemini en Configuración.');configureCloud();}
function loadSettingsUI(){$('#cfgModel').value=settings.model;$('#cfgVideoModel').value=settings.videoModel;$('#cfgGoogleClientId').value=settings.googleClientId;$('#cfgBackendUrl').value=settings.backendUrl;$('#cfgAppToken').value=sessionStorage.getItem(TOKEN_KEY)||'';}
function saveSettings(){settings={model:$('#cfgModel').value.trim(),videoModel:$('#cfgVideoModel').value.trim(),googleClientId:$('#cfgGoogleClientId').value.trim(),backendUrl:$('#cfgBackendUrl').value.trim().replace(/\/+$/,'')};localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings));sessionStorage.setItem(TOKEN_KEY,$('#cfgAppToken').value.trim());cfgReady();$('#settingsDialog').close();toast('Configuración cloud guardada.');}
async function diagnostics(){try{ensureApi();const h=await cloudJSON('/health');$('#localDiagnostics').textContent=`Backend: OK · Gemini: ${h.geminiConfigured?'configurado':'FALTA CLAVE'} · Token de app: ${h.tokenRequired?'requerido':'opcional'}`;if(!h.geminiConfigured)toast('Agrega GEMINI_API_KEY como secreto del Worker.','bad');else toast('Backend cloud conectado.');}catch(e){$('#localDiagnostics').textContent='Backend no disponible: '+String(e?.message||e);fail(e)}}

function renderFiles(){
  const gl=$('#guideList');gl.innerHTML=''; if(!state.guideFiles.length){gl.textContent='Aún no hay guías.';gl.className='file-list empty'}else{gl.className='file-list';state.guideFiles.forEach((f,i)=>{const d=document.createElement('div');d.className='file-item';d.innerHTML=`<div><b>${esc(f.name)}</b><small> · ${bytes(f.size)}</small></div><button class="btn ghost small" data-rm-guide="${i}">Quitar</button>`;gl.appendChild(d)})}
  const sl=$('#sourceFileInfo');sl.innerHTML='';if(!state.sourceFile){sl.textContent='Aún no hay origen.';sl.className='file-list empty'}else{sl.className='file-list';sl.innerHTML=`<div class="file-item"><div><b>${esc(state.sourceFile.name)}</b><small> · ${bytes(state.sourceFile.size)}</small></div><button class="btn ghost small" data-rm-source>Quitar</button></div>`}
  $('#uploadHint').textContent=state.guideFiles.length&&(state.sourceFile||state.sourceMode==='drive'&&$('#driveReference').value.trim()||state.sourceMode==='youtube'&&$('#youtubeReference').value.trim())?'Listo para analizar.':'Carga al menos una guía y un origen.';
}

async function prepareGuides(){const out=[];for(let i=0;i<state.guideFiles.length;i++){setProgress(.05+.22*(i/state.guideFiles.length),`Leyendo guía ${i+1}/${state.guideFiles.length}: ${state.guideFiles[i].name}`);const r=await buildRecord(state.guideFiles[i],'guide');r.structure=extractGuideStructure(r.text);out.push(r)}state.guides=out;return out}
async function prepareSource(){
 let file=state.sourceFile, ref='';
 if(state.sourceMode==='youtube'){
  const youtubeUrl=$('#youtubeReference').value.trim();if(!youtubeUrl)throw new Error('Pega una URL pública de YouTube.');
  const result=await processVideo({youtubeUrl,model:settings.videoModel,onProgress:(m,p)=>setProgress(.28+.28*p,m)});
  state.engineJob=result.jobId;state.videoFile=null;state.videoTranscript=result.transcript;
  state.sourceRecord={name:result.name,kind:'video',fingerprint:result.fingerprint,text:renderTranscriptAsSource(result.transcript,result.name),video_actions:result.transcript.actions};
  return state.sourceRecord;
 }
 if(state.sourceMode==='drive'){
  ref=$('#driveReference').value.trim();if(!ref)throw new Error('Pega la URL del archivo de Drive.');
  const meta=await getDriveMetadata(ref);state.driveMeta=meta;
  if(!meta.mimeType?.startsWith('video/')){const dl=await downloadDriveFile(ref,(m,p)=>setProgress(.28+.16*p,m));file=dl.blob;ref='';}
 }
 if(ref||file&&(isVideoName(file.name)||file.type.startsWith('video/'))){
  const report=(m,p)=>setProgress(.28+.28*p,m);
  const result=await processVideo({file:ref?null:file,driveReference:ref||undefined,model:settings.videoModel,onProgress:report});
  state.engineJob=result.jobId;state.videoFile=ref?null:file;state.videoTranscript=result.transcript;
  if(!result.transcript.actions.length)toast('Gemini no identificó acciones operativas en el video. Revisa que el contenido sea visible y narrado.','bad',10000);
  state.sourceRecord={name:result.name,kind:'video',fingerprint:result.fingerprint,text:renderTranscriptAsSource(result.transcript,result.name),video_actions:result.transcript.actions};
  return state.sourceRecord;
 }
 if(!file)throw new Error('Selecciona el archivo de origen.');
 state.engineJob=null;state.videoFile=null;state.videoTranscript=null;
 state.sourceRecord=await buildRecord(file,'source');return state.sourceRecord;
}

async function analyze(){try{ensureApi();if(!state.guideFiles.length)throw new Error('Carga al menos una guía.');if(state.guideFiles.length>(base.MAX_GUIDES||8))throw new Error(`Máximo ${base.MAX_GUIDES||8} guías.`);if(state.sourceMode==='local'&&!state.sourceFile)throw new Error('Carga el documento o video de origen.');if(state.sourceMode==='drive'&&!$('#driveReference').value.trim())throw new Error('Pega la URL del archivo de Drive.');if(state.sourceMode==='youtube'&&!$('#youtubeReference').value.trim())throw new Error('Pega una URL pública de YouTube.');
  progressStart('Analizando guías y origen');setProgress(.03,'Validando archivos…');const guides=await prepareGuides();const source=await prepareSource();setProgress(.58,'Seleccionando la guía aplicable y comparando evidencia…');const analysis=await analyzeLocal({model:settings.model,guides,source});state.analysis=analysis;state.answers=[];state.finalDocument=null;state.audit=null;state.docxBlob=null;state.pdfBlob=null;await saveSnapshot();renderAnalysis();setStep(2);show('#stageAnalysis',true);$('#stageAnalysis').scrollIntoView({behavior:'smooth'});progressEnd();toast('Análisis completado.')
}catch(e){fail(e)}}

function renderAnalysis(){const a=state.analysis;if(!a)return;$('#actionSection').innerHTML=(a.sections||[]).map(s=>`<option value="${s.order}">${esc(s.title)}</option>`).join('');const procedural=(a.sections||[]).find(s=>/procedimiento|desarrollo|paso|actividad|descripción/i.test(s.title));if(procedural)$('#actionSection').value=procedural.order;show('#actionSectionBox',!!state.videoTranscript);const req=(a.sections||[]).filter(s=>s.required).length,missing=(a.sections||[]).filter(s=>s.status==='faltante').length,partial=(a.sections||[]).filter(s=>s.status==='parcial').length;
  const actionCount=state.videoTranscript?.actions?.length||0;const captureCount=(state.videoTranscript?.actions||[]).filter(x=>captureReference(x).recommended).length;
  $('#analysisSummary').innerHTML=metric('Proceso',a.detected_process)+metric('Guía principal',a.selected_guide_name)+metric(state.videoTranscript?'Acciones video':'Secciones',String(state.videoTranscript?actionCount:(a.sections?.length||0)))+metric(state.videoTranscript?'Capturas sugeridas':'Brechas',String(state.videoTranscript?captureCount:(missing+partial)));
  const wh=$('#analysisWarnings');wh.innerHTML='';(a.warnings||[]).forEach(x=>warn(wh,x));
  const host=$('#analysisSections');host.innerHTML='';(a.sections||[]).forEach(s=>{const d=document.createElement('div');d.className='analysis-section';const cls=s.status==='completo'?'good':s.status==='parcial'?'warn':'bad';d.innerHTML=`<div class="section-toolbar"><h3>${s.order}. ${esc(s.title)}</h3><span class="badge ${cls}">${esc(s.status)}</span></div><div class="badges">${(s.criteria||[]).map(x=>`<span class="badge">${esc(x)}</span>`).join('')}</div>${s.draft_content?`<p>${esc(s.draft_content)}</p>`:''}${(s.evidence||[]).length?`<div class="evidence"><b>Evidencia:</b> ${(s.evidence||[]).map(esc).join(' · ')}</div>`:''}`;host.appendChild(d)});
  const questions=[];(a.sections||[]).forEach(s=>(s.missing_questions||[]).forEach(q=>questions.push({...q,section_title:s.title})));const qh=$('#questionList');qh.innerHTML='';show('#questionArea',questions.length>0);questions.forEach((q,i)=>{const d=document.createElement('div');d.className='question-card';d.innerHTML=`<label>${esc(q.question)} ${q.required?'<span class="badge bad">requerida</span>':''}</label><p>${esc(q.category||'')} · ${esc(q.why_needed||'')}</p><textarea class="textarea question-answer" rows="2" data-q="${i}" data-section="${esc(q.section_title)}" data-question="${esc(q.question)}" placeholder="Escribe la respuesta verificable…"></textarea>`;qh.appendChild(d)});
}
function metric(k,v){return `<div class="metric"><span>${esc(k)}</span><b>${esc(v||'—')}</b></div>`}
function collectAnswers(){return $$('.question-answer').map(x=>({section_title:x.dataset.section,question:x.dataset.question,answer:x.value.trim()})).filter(x=>x.answer)}

async function generateDraft(){try{ensureApi();if(!state.analysis)throw new Error('Primero analiza los archivos.');state.answers=collectAnswers();progressStart('Generando borrador');setProgress(.12,'Preparando análisis, respuestas y estructura exacta…');setProgress(.3,'Redactando secciones con trazabilidad…');const doc=await generateDraftLocal({model:settings.model,guides:state.guides,source:state.sourceRecord,analysis:state.analysis,answers:state.answers,onProgress:m=>setProgress(.4,m)});if(state.videoTranscript)attachActions(doc,state.videoTranscript.actions,Number($('#actionSection').value));state.finalDocument=doc;await saveSnapshot();renderDraft();setStep(3);show('#stageDraft',true);$('#stageDraft').scrollIntoView({behavior:'smooth'});progressEnd();toast('Borrador generado.') }catch(e){fail(e)}}

function joinLines(a){return (a||[]).join('\n')}
function renderDraft(){const d=state.finalDocument;if(!d)return;$('#docTitle').value=d.title||'';$('#docSubtitle').value=d.subtitle||'';$('#docIntro').value=d.introductory_note||'';const host=$('#draftSections');host.innerHTML='';(d.sections||[]).forEach((s,i)=>{const el=document.createElement('div');el.className='draft-section';el.dataset.order=s.order;el.innerHTML=`<div class="section-toolbar"><h3>${s.order}. ${esc(s.title)}</h3><button class="btn secondary small regen-section" data-order="${s.order}">✨ Regenerar sección</button></div><div class="draft-grid"><label class="full">Párrafos<textarea class="textarea f-paragraphs" rows="5">${esc(joinLines(s.paragraphs))}</textarea></label><label>Pasos numerados<textarea class="textarea f-numbered" rows="6">${esc(joinLines(s.numbered_items))}</textarea></label><label>Viñetas<textarea class="textarea f-bullets" rows="6">${esc(joinLines(s.bullets))}</textarea></label><label class="full">Tablas (JSON)<textarea class="textarea table-editor f-tables" rows="5">${esc(JSON.stringify(s.tables||[],null,2))}</textarea></label><label class="full">Sustento<textarea class="textarea f-basis" rows="2">${esc(joinLines(s.source_basis))}</textarea></label></div>`;host.appendChild(el)});wireDraftAutosave()}
function lines(v){return String(v||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean)}
function readDraftFromDom(){const d=normalizeFinal(state.finalDocument||{});d.title=$('#docTitle').value.trim();d.subtitle=$('#docSubtitle').value.trim();d.introductory_note=$('#docIntro').value.trim();d.sections=$$('.draft-section').map((el,i)=>{const old=d.sections[i]||{};let tables=[];try{tables=JSON.parse($('.f-tables',el).value||'[]')}catch{throw new Error('Corrige el JSON de tablas de la sección '+old.title)}return {...old,order:Number(el.dataset.order)||i+1,paragraphs:lines($('.f-paragraphs',el).value),numbered_items:lines($('.f-numbered',el).value),bullets:lines($('.f-bullets',el).value),tables:Array.isArray(tables)?tables:[],source_basis:lines($('.f-basis',el).value)}});return d}
const saveDraftDebounced=debounce(async()=>{if(!state.finalDocument)return;state.finalDocument=readDraftFromDom();await saveSnapshot()},450);
function wireDraftAutosave(){$$('#stageDraft textarea, #stageDraft input').forEach(x=>x.addEventListener('input',saveDraftDebounced));$$('.regen-section').forEach(b=>b.addEventListener('click',()=>regenOne(Number(b.dataset.order),b)))}
async function regenOne(order,button){try{ensureApi();state.finalDocument=readDraftFromDom();button.disabled=true;button.textContent='Regenerando…';const sec=await regenerateSection({model:settings.model,guides:state.guides,source:state.sourceRecord,analysis:state.analysis,answers:state.answers,document:state.finalDocument,sectionOrder:order});state.finalDocument.sections=state.finalDocument.sections.map(s=>Number(s.order)===order?sec:s);renderDraft();await saveSnapshot();toast('Sección regenerada.')}catch(e){fail(e)}finally{if(button){button.disabled=false;button.textContent='✨ Regenerar sección'}}}

async function finalize(){try{ensureApi();state.finalDocument=readDraftFromDom();progressStart('Auditando y preparando documento final');setProgress(.14,'Guardando tus modificaciones…');setProgress(.30,'Auditando el documento completo contra la guía…');const audit=await auditLocal({model:settings.model,guides:state.guides,source:state.sourceRecord,analysis:state.analysis,document:state.finalDocument});state.audit=audit;state.finalDocument.validation=audit.validation||state.finalDocument.validation;state.finalDocument.warnings=[...new Set([...(state.finalDocument.warnings||[]),...(audit.warnings||[])])];await buildOutputs();}catch(e){fail(e)}}

async function buildOutputs(){if(state.videoTranscript){assertCoverage(state.finalDocument,state.videoTranscript.actions);assertCaptureReferences(state.finalDocument,state.videoTranscript.actions);}progressStart('Generando Word y PDF');setProgress(.86,'Aplicando formato institucional y referencias de video…');const guide=state.guides[state.analysis.selected_guide_index];const template=guide?.extension==='docx'?guide.file:null;state.docxBlob=await createDocx(state.finalDocument,{templateFile:template});setProgress(.93,'Creando PDF paginado…');try{state.pdfBlob=await createPdf(state.finalDocument)}catch(e){state.pdfBlob=null;state.finalDocument.warnings.push('PDF no disponible: '+e.message);}await saveSnapshot();renderFinal();setStep(4);show('#stageFinal',true);$('#stageFinal').scrollIntoView({behavior:'smooth'});progressEnd();toast('Documento final generado con minutos exactos para capturas manuales.');}

function renderFinal(){const d=state.finalDocument,a=state.audit||{};const counts={cumple:0,parcial:0,no_aplica:0};(d.validation||[]).forEach(x=>{if(counts[x.status]!=null)counts[x.status]++});const total=Object.values(counts).reduce((x,y)=>x+y,0);const actionCount=state.videoTranscript?.actions?.length||0;const captureCount=(state.videoTranscript?.actions||[]).filter(x=>captureReference(x).recommended).length;$('#finalSummary').innerHTML=metric('Secciones',String(d.sections?.length||0))+metric(state.videoTranscript?'Acciones trazadas':'Cumple',String(state.videoTranscript?actionCount:counts.cumple))+metric(state.videoTranscript?'Capturas sugeridas':'Parcial',String(state.videoTranscript?captureCount:counts.parcial))+metric('Criterios cumplen',total?`${counts.cumple}/${total}`:'—');$('#finalCompliance').textContent=total?`${counts.cumple}/${total} criterios cumplen`:'Documento generado';$('#auditSummary').textContent=a.editorial_summary||'Documento generado con trazabilidad a la guía y al origen.';const wh=$('#finalWarnings');wh.innerHTML='';(d.warnings||[]).forEach(x=>warn(wh,x));$('#docxSize').textContent=state.docxBlob?bytes(state.docxBlob.size):'DOCX';$('#pdfSize').textContent=state.pdfBlob?bytes(state.pdfBlob.size):'PDF';$('#finalPreview').innerHTML=previewHtml(d)}
function previewHtml(d){return `<article class="doc-preview"><h1>${esc(d.title)}</h1>${d.subtitle?`<p style="text-align:center"><i>${esc(d.subtitle)}</i></p>`:''}${d.introductory_note?`<p>${esc(d.introductory_note)}</p>`:''}${(d.sections||[]).map(s=>`<section><h2>${s.order}. ${esc(s.title)}</h2>${(s.paragraphs||[]).map(x=>`<p>${esc(x)}</p>`).join('')}${(s.numbered_items||[]).length?`<ol>${s.numbered_items.map(x=>`<li>${esc(x)}</li>`).join('')}</ol>`:''}${(s.bullets||[]).length?`<ul>${s.bullets.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}${(s.tables||[]).map(t=>`<h4>${esc(t.title||'')}</h4><table><thead><tr>${(t.headers||[]).map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${(t.rows||[]).map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table>`).join('')}</section>`).join('')}</article>`}


async function saveSnapshot(){const snap={engineJob:state.engineJob,videoTranscript:state.videoTranscript,analysis:state.analysis,answers:state.answers,finalDocument:state.finalDocument,audit:state.audit,sourceRecord:state.sourceRecord?{...state.sourceRecord,file:undefined}:null,guides:state.guides,savedAt:new Date().toISOString()};await idbSet('project-snapshot',snap)}
async function maybeRestore(){const s=await idbGet('project-snapshot');if(!s?.analysis)return;state.engineJob=s.engineJob||null;state.videoTranscript=s.videoTranscript||null;state.analysis=s.analysis;state.answers=s.answers||[];state.finalDocument=s.finalDocument||null;state.audit=s.audit||null;state.sourceRecord=s.sourceRecord||null;state.guides=s.guides||[];renderAnalysis();show('#stageAnalysis',true);setStep(state.finalDocument?3:2);if(state.finalDocument){renderDraft();show('#stageDraft',true)}toast('Se recuperó el último borrador guardado en este navegador. Vuelve a seleccionar las guías si necesitas regenerar Word/PDF.', 'good',5000)}

async function resetAll(){if(!confirm('¿Reiniciar el proceso y borrar checkpoints locales de este navegador?'))return;Object.assign(state,{sourceMode:'local',guideFiles:[],guides:[],sourceFile:null,sourceRecord:null,videoFile:null,videoTranscript:null,analysis:null,answers:[],finalDocument:null,audit:null,docxBlob:null,pdfBlob:null,driveMeta:null,engineJob:null});await idbClear();sessionStorage.removeItem('bot-v18-active-video');$('#guideFiles').value='';$('#sourceFile').value='';$('#driveReference').value='';if($('#youtubeReference'))$('#youtubeReference').value='';renderFiles();['#stageAnalysis','#stageDraft','#stageFinal','#progressPanel'].forEach(x=>show(x,false));setStep(1);window.scrollTo({top:0,behavior:'smooth'});toast('Proceso reiniciado.')}

function wire(){
  $('#appTitle').textContent=base.title||'Generador documental inteligente';$('#appSubtitle').textContent=base.subtitle||'';$('#maxGuidesLabel').textContent=base.MAX_GUIDES||8;cfgReady();loadSettingsUI();renderFiles();
  $('#btnSettings').addEventListener('click',()=>{loadSettingsUI();$('#settingsDialog').showModal()});$('#btnSaveSettings').addEventListener('click',saveSettings);$('#btnClearSettings').addEventListener('click',()=>{localStorage.removeItem(SETTINGS_KEY);sessionStorage.removeItem(TOKEN_KEY);settings={...defaultSettings};configureCloud();loadSettingsUI();cfgReady();toast('Configuración cloud borrada.')});$('#btnReset').addEventListener('click',resetAll);
  $('#guideFiles').addEventListener('change',e=>{const incoming=[...e.target.files].filter(f=>['pdf','docx','txt'].includes(ext(f.name)));state.guideFiles=[...state.guideFiles,...incoming].slice(0,base.MAX_GUIDES||8);e.target.value='';renderFiles()});
  $('#sourceFile').addEventListener('change',e=>{state.sourceFile=e.target.files?.[0]||null;renderFiles()});
  document.addEventListener('click',e=>{const rg=e.target.closest('[data-rm-guide]');if(rg){state.guideFiles.splice(Number(rg.dataset.rmGuide),1);renderFiles()}if(e.target.closest('[data-rm-source]')){state.sourceFile=null;$('#sourceFile').value='';renderFiles()}});
  $$('.seg[data-source-mode]').forEach(b=>b.addEventListener('click',()=>{state.sourceMode=b.dataset.sourceMode;$$('.seg[data-source-mode]').forEach(x=>x.classList.toggle('active',x===b));show('#localSourcePane',state.sourceMode==='local');show('#driveSourcePane',state.sourceMode==='drive');show('#youtubeSourcePane',state.sourceMode==='youtube');renderFiles()}));
  $('#driveReference').addEventListener('input',renderFiles);$('#youtubeReference').addEventListener('input',renderFiles);$('#btnConnectDrive').addEventListener('click',async()=>{try{await connectDrive(settings.googleClientId);$('#driveStatus').textContent='Conectado';toast('Google Drive conectado.')}catch(e){fail(e)}});if(isDriveConnected())$('#driveStatus').textContent='Conectado';
  $('#btnAnalyze').addEventListener('click',guarded(analyze));$('#btnGenerateDraft').addEventListener('click',guarded(generateDraft));$('#btnBackAnalysis').addEventListener('click',()=>$('#stageAnalysis').scrollIntoView({behavior:'smooth'}));$('#btnFinalize').addEventListener('click',guarded(finalize));
  $('#btnExportAnalysis').addEventListener('click',()=>state.analysis&&downloadBlob(jsonBlob(state.analysis),'analisis_guia.json'));
  $('#btnDownloadDocx').addEventListener('click',()=>state.docxBlob&&downloadBlob(state.docxBlob,`${safeName(state.finalDocument?.title)}.docx`));$('#btnDownloadPdf').addEventListener('click',()=>state.pdfBlob&&downloadBlob(state.pdfBlob,`${safeName(state.finalDocument?.title)}.pdf`));$('#btnDownloadProject').addEventListener('click',()=>downloadBlob(jsonBlob({version:'v18-cloud',guides:state.guides.map(g=>({...g,file:undefined})),sourceRecord:state.sourceRecord,videoTranscript:state.videoTranscript,engineJob:state.engineJob,analysis:state.analysis,answers:state.answers,finalDocument:state.finalDocument,audit:state.audit,source:{name:state.sourceRecord?.name,fingerprint:state.sourceRecord?.fingerprint},savedAt:new Date().toISOString()}),'proyecto_bot_documental_v18_cloud.json'));
  $('#importProject').addEventListener('change',async e=>{try{const file=e.target.files?.[0];if(!file)return;const project=JSON.parse(await file.text());if(project.version!=='v18-cloud'||!Array.isArray(project.guides)||!project.analysis)throw new Error('Proyecto V18 cloud inválido');Object.assign(state,{guides:project.guides,analysis:project.analysis,sourceRecord:project.sourceRecord,answers:project.answers||[],videoTranscript:project.videoTranscript||null,engineJob:project.engineJob||null,finalDocument:project.finalDocument?normalizeFinal(project.finalDocument):null,audit:project.audit||null});await saveSnapshot();await maybeRestore();toast('Proyecto V18 importado.');}catch(e){fail(e)}});
  ['dragenter','dragover'].forEach(ev=>$$('.dropzone').forEach(z=>z.addEventListener(ev,e=>{e.preventDefault();z.classList.add('drag')})));['dragleave','drop'].forEach(ev=>$$('.dropzone').forEach(z=>z.addEventListener(ev,e=>{e.preventDefault();z.classList.remove('drag')})));
}

// Evitar ejecuciones simultáneas desde botones de proceso.
function guarded(fn){return async()=>{if(window.botBusy)return;window.botBusy=true;const buttons=$$('#btnAnalyze,#btnGenerateDraft,#btnFinalize,#btnReset');buttons.forEach(b=>b.disabled=true);try{await fn()}finally{buttons.forEach(b=>b.disabled=false);window.botBusy=false}}}
wire();maybeRestore().catch(console.warn);$('#btnDiagnostics').addEventListener('click',diagnostics);
